# 1. Create a 3x3x3 array with random values 

In [5]:
import numpy as np

In [6]:

x=np.random.random((3,3,3))
print(x)

[[[0.44900196 0.40028937 0.02641591]
  [0.72476488 0.29737266 0.0256221 ]
  [0.37453382 0.08251018 0.33913769]]

 [[0.08992586 0.40291886 0.8255448 ]
  [0.97246551 0.19575626 0.8597649 ]
  [0.8147459  0.87503562 0.6378521 ]]

 [[0.88775254 0.39667863 0.06461094]
  [0.11075313 0.99168147 0.159099  ]
  [0.69351899 0.14871473 0.31269611]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
matrix = np.zeros((5,5))
matrix = np.diag(1+np.arange(4),k = -1)
print('Matrix with 1,2,3,4 just below Diagonal:\n\n', matrix)

Matrix with 1,2,3,4 just below Diagonal:

 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[2::,1::2]=1
print('check board pattern:\n')
print(x)

check board pattern:

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]]


# 4. Normalize a 5x5 random matrix

In [15]:
x= np.random.randn(5,5)
print("Original Array:\n")
print(x)

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

print("\nAfter normalization:\n")
print(x)

Original Array:

[[ 2.25808539  0.07392385  0.55792187 -1.7966044   0.66437399]
 [ 0.35660885 -0.82024272  1.24432564  0.14733583  0.47524217]
 [-0.58531296 -1.648787   -1.09622283  0.13465093  0.85579156]
 [-0.22689871  1.90384904 -0.28125494 -2.1428089   0.9366154 ]
 [ 0.22057098  0.42892203 -0.48881934 -0.41796507  1.20113393]]

After normalization:

[[1.         0.50370052 0.61367772 0.07866685 0.63786647]
 [0.56793406 0.30052214 0.76964687 0.52038167 0.5948907 ]
 [0.35390442 0.11225489 0.23781214 0.51749933 0.68136162]
 [0.43534565 0.9195081  0.42299447 0.         0.69972694]
 [0.53702264 0.58436553 0.37583033 0.3919303  0.75983257]]


# 5.  How to find common values between two arrays?

In [ ]:
array1=np.array([0,10,20,40,])
array2=[10,30,40]
print("array1:",array1)
print('array1:',array2)

# 6.How to get the dates of yesterday, today and tomorrow?

In [21]:
import datetime as dt
today=dt.date.today()
yesterday=today - dt.timedelta(days=1)
tomorrow=today+dt.timedelta(days=1)

print('yesterdays:',yesterday)
print('today:',today)
print('tomorrow:',tomorrow)

yesterdays: 2020-11-01
today: 2020-11-02
tomorrow: 2020-11-03


# 7. Consider two random array A and B, check if they are equal

In [22]:
a=np.array([[1,3,5],[7,4,9]])
b=np.array([[1,3,5],[7,4,9]])
print('array1:\n',a)
print('array2:\n',b)
print('\nresult is True if the arrays are equal \nresult is false if the arrays are not equal')
np.array_equal(a,b)

array1:
 [[1 3 5]
 [7 4 9]]
array2:
 [[1 3 5]
 [7 4 9]]

result is True if the arrays are equal 
result is false if the arrays are not equal


True

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [29]:
vector=np.array([1,45,867,90,48,94,100,166,867,110])
print('vector:',vector)
print('length of vector:',len(vector))

vector_max=vector.max()
print('maximum value:',vector_max)
index=np.where(vector==vector_max)
vector[index]=0
print('replacing {} by 0: {}'.format(vector_max,vector))

vector: [  1  45 867  90  48  94 100 166 867 110]
length of vector: 10
maximum value: 867
replacing 867 by 0: [  1  45   0  90  48  94 100 166   0 110]


# 9. How to print all the values of an array?

In [31]:
#1-D Array
print('for 1-D Array:')
x=np.array([12,34,67,89])
for i in range(len(x)):
    print(f'The element at index {i} is: {x[i]}')
    
#2-D Array

print('\nfor 2-D Array:')
y=np.array([[1,2,3],[4,5,6],[7,8,9],[11,22,33]])
for i in range(len(y)):
    print(f'the element at index {i} is: {y[i]}')

for 1-D Array:
The element at index 0 is: 12
The element at index 1 is: 34
The element at index 2 is: 67
The element at index 3 is: 89

for 2-D Array:
the element at index 0 is: [1 2 3]
the element at index 1 is: [4 5 6]
the element at index 2 is: [7 8 9]
the element at index 3 is: [11 22 33]


# 10.Subtract the mean of each row of a matrix

In [32]:
arr = np.array([[1, 100, 0, 0], [2, 110, 0, 0], [3, 120, 0, 0]])
print('Initial Array:\n', arr)
print('Mean of Each row: ',arr.mean(axis=1))
mean = arr - arr.mean(axis=1, keepdims=True) 
print('\nResultant Matrix After Subtracting Mean:\n',mean)

Initial Array:
 [[  1 100   0   0]
 [  2 110   0   0]
 [  3 120   0   0]]
Mean of Each row:  [25.25 28.   30.75]

Resultant Matrix After Subtracting Mean:
 [[-24.25  74.75 -25.25 -25.25]
 [-26.    82.   -28.   -28.  ]
 [-27.75  89.25 -30.75 -30.75]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [33]:
Z = np.ones(10)
print("Initial Vector:\n",Z)
I = np.random.randint(0, len(Z),20)
print("Random Values:\n",I)
Z += np.bincount(I, minlength=len(Z))
print("Resultant Vector:\n",Z)

Initial Vector:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Random Values:
 [8 8 4 9 6 9 1 4 2 4 2 3 0 1 3 4 0 5 6 0]
Resultant Vector:
 [4. 3. 3. 3. 5. 2. 3. 1. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [34]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

print("Array A:\n", A)
print("Array B:\n", B)

print('\nDot product:\n',np.dot(A,B))
dot = np.diag(np.dot(A, B))
print('\nThe Diagonal Elements are:\n', dot)

Array A:
 [[5 3 3]
 [8 3 3]
 [6 2 7]]
Array B:
 [[3 2 3]
 [9 0 0]
 [3 2 9]]

Dot product:
 [[51 16 42]
 [60 22 51]
 [57 26 81]]

The Diagonal Elements are:
 [51 22 81]


# 13.How to find the most frequent value in an array?

In [35]:
Z = np.random.randint(0,10,30)
print ("Array:", Z)
print('Most Frequent Value:', np.bincount(Z).argmax())

Array: [2 5 2 0 4 0 4 8 5 6 1 0 9 7 2 1 4 1 7 7 5 3 5 9 0 3 5 5 4 5]
Most Frequent Value: 5


# 14.How to get the n largest values of an array

In [36]:
Z = np.arange(100)
np.random.shuffle(Z)
n = int(input('Enter the value of n: '))
print(f"{n} Largest values in array: ", Z[np.argsort(Z)[-n:]])

Enter the value of n: 5
5 Largest values in array:  [95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [38]:
print('for a single array:\n')
x3=np.array([['vivek',10,20],['rajesh',30,40],['vineet',50,60]])
print('regular array:\n',x3)
rec=np.core.records.fromarrays(x3.T,names='name,msk1,msk2',formats='S80,i8,i8')
print('\nrecord array:',rec)
print('type of result:',type(rec))

for a single array:

regular array:
 [['vivek' '10' '20']
 ['rajesh' '30' '40']
 ['vineet' '50' '60']]

record array: [(b'vivek', 10, 20) (b'rajesh', 30, 40) (b'vineet', 50, 60)]
type of result: <class 'numpy.recarray'>


In [40]:
x1=np.array([1,2,3,4,5])
x2=np.array(['v','i','v','e','k'])

print('regular arary 1:',x1)
print('regular array 2:',x2)

records = np.core.records.fromarrays([x1,x2],names='col1,col2')

print('\nrecord Array:',records)
print('type of result:',type(records))

regular arary 1: [1 2 3 4 5]
regular array 2: ['v' 'i' 'v' 'e' 'k']

record Array: [(1, 'v') (2, 'i') (3, 'v') (4, 'e') (5, 'k')]
type of result: <class 'numpy.recarray'>
